#!/usr/bin/python2

import pygtk
import gtk

import widgets.WindowMain
import database.DBVoc
import config

if __name__ == "__main__":
	db      = database.DBVoc(config.getFilename('Database'))
	winMain = widgets.WindowMain(db)

	gtk.mainloop()

