#!/usr/bin/python

from gi.repository import Gtk

import widgets
import database
import config

if __name__ == "__main__":
	db      = database.DBVoc(config.getFilename('Database'))
	winMain = widgets.WindowMain(db)

	winMain.show_all()

	Gtk.mainloop()

