#!/usr/bin/python2

import pygtk
import gtk

import widgets.windowMain
import database.dbVoc

if __name__ == "__main__":
	db      = database.dbVoc.DBVoc('test.db')
	winMain = widgets.windowMain.WindowMain(db)

	gtk.mainloop()

