#!/usr/bin/python2

import pygtk
import gtk

import widgets.WindowMain
import database.DBVoc

if __name__ == "__main__":
	db      = database.DBVoc('test.db')
	winMain = widgets.WindowMain(db)

	gtk.mainloop()

